<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>cf8cd39b-93a6-4259-bc84-e00e8f9b8766</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="selenium-firefox-profile\**" />
    <Content Remove="selenium-firefox-profile\**" />
    <EmbeddedResource Remove="selenium-firefox-profile\**" />
    <None Remove="selenium-firefox-profile\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="NZPropertyScraper" Version="1.0.6" />
    <PackageReference Include="QuestPDF" Version="2026.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DRIVERS\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="DRIVERS\geckodriver.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
